---
title: "Multithreading"
author:
    name: "Emanuele Natale"
    email: emanuele.natale@univ-cotedazur.fr
    affiliation: CNRS, I3S, INRIA, UCA
date: "15 04 2025"
engine: julia
julia:
  exeflags: [
    "--procs=1",
    "--threads=4"
  ]
format:
  revealjs:
    theme: dark
    code-line-numbers: false
    slide-number: true
    overview: true
    scrollable: true
execute:
    echo: true
    freeze: auto
    error: true
---

## Recall `mthr_sum1`

```{julia}
using .Threads
@show nthreads()

function mthr_sum1(A)
    r = 0.0
    @threads for i in eachindex(A)
        @inbounds r += A[i]
    end
    return r
end

A = rand(10_000_000)
@show mthr_sum1(A) ≈ sum(A)
```

## Key takeaways from `mthr_sumX`:

* Beware shared state across threads
  * Protect yourself by using atomics (or [locks/mutexes](https://docs.julialang.org/en/v1/base/multi-threading/#Synchronization-Primitives-1))
  * Better: separate states manually in `@threads for i in 1:nthreads()`
    * Simpler: use array, with separate entries per thread

## Recall `mthr_sum4`

```{julia}
function mthr_sum4(A)
    R = zeros(eltype(A), nthreads())
    @threads for i in eachindex(A)
        @inbounds R[threadid()] += A[i]
    end
    r = 0.0
    for i in eachindex(R)
        @inbounds r += R[i]
    end
    return r
end

mthr_sum4(A)
@show mthr_sum4(A) ≈ sum(A)
```

## Beware of global state: $\pi$ example

How can we compute $\pi$?

::: {.fragment}
```{julia}
using BenchmarkTools

function serialpi(n)
    inside = 0
    for i in 1:n
        x, y = rand(), rand()
        inside += (x^2 + y^2 <= 1)
    end
    return 4 * inside / n
end

@btime serialpi(100_000_000)
```
:::

## Naive multithreaded version

```{julia}
function threadedpi(n)
    inside = zeros(Int, nthreads())
    @threads for i in 1:n
        x, y = rand(), rand()
        @inbounds inside[threadid()] += (x^2 + y^2 <= 1)
    end
    return 4 * sum(inside) / n
end

@btime threadedpi(100_000_000)
```

## Why is it so slow?

:::: {.columns}

::: {.column width="50%"}
```{julia}
#| output: false
import Random
Random.seed!(0)
N = 100
Rserial = zeros(N)
for i in 1:N
    Rserial[i] = rand()
end
```
:::

::: {.column width="50%"}
::: {.fragment}
```{julia}
#| output: false
Random.seed!(0)
Rthreaded = zeros(N)
@threads for i in 1:N
    Rthreaded[i] = rand()
end
```
:::
:::

::::

::: {.fragment}
```{julia}
@show Set(Rserial) == Set(Rthreaded)
@show indexin(Rserial, Rthreaded)
```
:::

## Solution: use separate RNGs

```{julia}
const ThreadRNG = Vector{Random.MersenneTwister}(undef, nthreads())
@threads for i in 1:nthreads()
    ThreadRNG[Threads.threadid()] = Random.MersenneTwister()
end

function threadedpi2(n)
    inside = zeros(Int, nthreads())
    len, rem = divrem(n, nthreads())
    rem == 0 || error("use a multiple of $(nthreads()), please!")
    @threads for i in 1:nthreads()
        rng = ThreadRNG[threadid()]
        v = 0
        for j in 1:len
            x, y = rand(rng), rand(rng)
            v += (x^2 + y^2 <= 1)
        end
        inside[threadid()] = v
    end
    return 4 * sum(inside) / n
end

@btime threadedpi2(100_000_000)
```

## Oversubscription

Remember: BLAS is already multithreaded.

```{julia}
Ms = [rand(1000, 1000) for _ in 1:100]
function serial_matmul(As)
    first_idxs = zeros(length(As))
    for i in eachindex(As)
        @inbounds first_idxs[i] = (As[i]'*As[i])[1]
    end
    first_idxs
end

@btime serial_matmul(Ms);
```

## Multithreaded BLAS
```{julia}
using LinearAlgebra
BLAS.set_num_threads(nthreads())

function threaded_matmul(As)
  first_idxs = zeros(length(As))
  @threads for i in eachindex(As)
    @inbounds first_idxs[i] = (As[i]'*As[i])[1]
  end
  first_idxs
end

@btime threaded_matmul(Ms);
```

```{julia}
BLAS.set_num_threads(1)
@btime threaded_matmul(Ms)
@btime serial_matmul(Ms);
```

## Beware of false sharing

```{julia}
function mthr_sum5(x)
    partsum = zeros(eltype(x), nthreads())
    @threads for i in eachindex(x)
        @inbounds partsum[threadid()] += x[i]
    end
    return sum(partsum)
end

A = rand(10_000_000)
@btime mthr_sum5($A)
```

## In theory this should be better...

:::: {.columns}
::: {.column width="50%"}
```{julia}
function mthr_sum6(x)
  gap = 8  # Adjust based on cache line size
  partsum = zeros(eltype(x), nthreads()*gap)
  @threads for i in eachindex(x)
    idx = (threadid()-1)*gap + 1
    @inbounds partsum[idx] += x[i]
  end
  return sum(partsum)
end

@btime mthr_sum6($A)
```
:::

::: {.column width="50%"}
```{julia}
function mthr_sum7(x)
  nth = nthreads()
  partsum = zeros(eltype(x), nth)
  @threads for t in 1:nth
    local_sum = zero(eltype(x))
    for i in t:nth:length(x)
      local_sum += x[i]
    end
    partsum[t] = local_sum
  end
  return sum(partsum)
end

@btime mthr_sum7($A)
```
:::
::::

## Keep in mind

* Multithreading: start Julia with `JULIA_NUM_THREADS` and tack a `@threads` on loop
* Beware
    * to set `JULIA_NUM_THREADS` appropiately
    * of shared state (for performance and correctness)
    * of global state (can be far from obvious)
    * of false sharing (if Julia/LLVM don't handle it)
* Think carefully about how to design parallel algorithms
